puts "🌱 Seeding spices..."
Author.create(name: "Chuck Klosterman")
Author.create(name: "Kurt Vonnegut Jr.")
Author.create(name: "Will Wight")
Author.create(name: "T.J. Klune")
Book.create(name: "Sex, Drugs, and Cocoa Puffs: A Low Culture Manifesto",author: "Chuck Klosterman", genre: "Essays", author_id: 1)
Book.create(name: "Killing Yourself to Live: 85% of a True Story",author: "Chuck Klosterman", genre: "Essays", author_id: 1)
Book.create(name: "Slaughterhouse-Five", author: "Kurt Vonnegut Jr.", genre: "Science Fiction", author_id:2)
Book.create(name: "Breakfast of Champions", author: "Kurt Vonnegut Jr.", genre: "Science Fiction", author_id:2)
Book.create(name: "Cat's Cradle", author: "Kurt Vonnegut Jr.", genre: "Science Fiction", author_id:2)
Book.create(name: "A Man Without a Country", author: "Kurt Vonnegut Jr.", genre: "Essays", author_id:2)
Book.create(name: "Unsouled(Cradle #1)", author: "Will Wight", genre: "Fantasy", author_id: 3)
Book.create(name: "Soulsmith(Cradle #2)", author: "Will Wight", genre: "Fantasy", author_id: 3)
Book.create(name: "Blackflame(Cradle #3)", author: "Will Wight", genre: "Fantasy", author_id: 3)
Book.create(name: "Skysworn(Cradle #4)", author: "Will Wight", genre: "Fantasy", author_id: 3)
Book.create(name: "Ghostwater(Cradle #5)", author: "Will Wight", genre: "Fantasy", author_id: 3)
Book.create(name: "Underlord(Cradle #6)", author: "Will Wight", genre: "Fantasy", author_id: 3)
Book.create(name: "Uncrowned(Cradle #7)", author: "Will Wight", genre: "Fantasy", author_id: 3)
Book.create(name: "Wintersteel(Cradle #8)", author: "Will Wight", genre: "Fantasy", author_id: 3)
Book.create(name: "Bloodline(Cradle #9)", author: "Will Wight", genre: "Fantasy", author_id: 3)
Book.create(name: "Reaper(Cradle #10)", author: "Will Wight", genre: "Fantasy", author_id: 3)
Book.create("The House in the Cerulean Sea" author:"T.J. Klune", genre: "Fantasy", author_id: 4)
puts "✅ Done seeding!"
